on: pull_request

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@v1.1.0
      - name: Install package
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm lint
