name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Release please
        uses: googleapis/release-please-action@7987652d64b4581673a76e33ad5e98e3dd56832f # v4
        id: release
        with:
          release-type: simple

  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    environment: deploy
    steps:
      - uses: actions/checkout@v4
      - uses: shiron-dev/actions/setup-node@12c16ca22eb8fcc2f4ecf420d6fbe263d09e16e5 # v1.3.0
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build:pages
        run: pnpm run build:pages
      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@392082e81ffbcb9ebdde27400634aa004b35ea37 # v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy ./.vercel/output/static --project-name=links-shiron-dev
